---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-storage-operatorgroup
  namespace: openshift-storage
  annotations:
    ran.openshift.io/ztp-deploy-wave: "7"
spec:
  targetNamespaces:
  - openshift-storage

