---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "common-core"
  namespace: "policies-sub"
spec:
  bindingRules:
    # These policies will correspond to all clusters with this label:
    core: "true"
  sourceFiles:
    # Create operators policies that will be installed in all Core clusters
     
    #
    # Disable default operator catalogs
    #
    - fileName: OperatorHub.yaml
      remediationAction: enforce
      policyName: "disable-catalogs"
    - fileName: catalogSourceMgmt.yaml
      remediationAction: enforce
      policyName: "config-cs"
    - fileName: imageContentSourcePolicyMgmt.yaml
      remediationAction: enforce
      policyName: "config-icsp"
    - fileName: mgmtcluster-ca-bundle.yaml
      remediationAction: enforce
      policyName: "config-mgmtcluster-ca"
    - fileName: mgmtcluster-to-proxy.yaml
      remediationAction: enforce
      policyName: "config-mgmtcluster-to-proxy"
    - fileName: ClusterVersionMgmt.yaml
      remediationAction: enforce
      policyName: "config-update-service"
