---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "common-core"
  namespace: "policies-sub"
spec:
  bindingRules:
    # These policies will correspond to all clusters with this label:
    core: "true"
  sourceFiles:
    # Create operators policies that will be installed in all Core clusters
     
    #
    # Disable default operator catalogs
    #
    - fileName: OperatorHub.yaml
      policyName: "disable-catalogs"

    #
    # Enable logging
    # Some CRs being created in cluster specific PGT
    #
#    - fileName: ClusterLogNS.yaml
#      policyName: "logging-subscription"
#    - fileName: ClusterLogOperGroup.yaml
#      policyName: "logging-subscription"
#    - fileName: ClusterLogSubscription.yaml
#      policyName: "logging-subscription"
#      spec:
#        source: mgmtcluster-operator-index
#    - fileName: ClusterLogging.yaml
#      policyName: "logging-instance"
#      spec:
#        collection:
#          logs:
#            type: "fluentd"
#            fluentd: {}

    #
    # Enable monitoring
    # Some CRs being created in cluster specific PGT
    #
#    - fileName: MON/kafkaAdapNS.yaml
#      policyName: "monitor-subscription"
#    - fileName: MON/UserWorkLoad.yaml
#      policyName: "monitor-subscription"
#    - fileName: MON/kafkaAdapService.yaml
#      policyName: "kafka-adap-svc"
#    - fileName: MON/OcpMonitoring.yaml
#      policyName: "enable-monitoring"

    #
    # SR-IOV operator
    #
    - fileName: SriovSubscriptionNS.yaml
      policyName: "sriov-subscription"
    - fileName: SriovSubscriptionOperGroup.yaml
      policyName: "sriov-subscription"
    - fileName: SriovSubscription.yaml
      policyName: "sriov-subscription"
      spec:
        source: mgmtcluster-operator-index
    #
    # PAO operator
    #
    - fileName: PaoSubscriptionNS.yaml
      policyName: "pao-subscription"
    - fileName: PaoSubscriptionOperGroup.yaml
      policyName: "pao-subscription"
    - fileName: PaoSubscription.yaml
      policyName: "pao-subscription"
      spec:
        source: mgmtcluster-operator-index
    - fileName: PAO/pao-master.yaml
      policyName: "pao-profile"
    - fileName: PAO/pao-profile1.yaml
      policyName: "pao-profile"
    - fileName: PAO/pao-profile2.yaml
      policyName: "pao-profile"
    #
    # CNV operator
    #
#    - fileName: CNV/CnvNS.yaml
#      policyName: "cnv-subscription"
#    - fileName: CNV/CnvOperGroup.yaml
#      policyName: "cnv-subscription"
#    - fileName: CNV/CnvSubscription.yaml
#      policyName: "cnv-subscription"
#      spec:
#        source: mgmtcluster-operator-index
#    - fileName: CNV/CnvHyperConverged.yaml
#      policyName: "cnv-subscription"
    #
    # LSO operator
    #
    - fileName: LSO/LsoNS.yaml
      policyName: "lso-subscription"
    - fileName: LSO/LsoOperGroup.yaml
      policyName: "lso-subscription"
    - fileName: LSO/LsoSubscription.yaml
      policyName: "lso-subscription"
      spec:
        source: mgmtcluster-operator-index
    - fileName: LSO/LsoVolumeSet.yaml
      policyName: "lso-subscription"
    #
    # ODF operator
    #
    - fileName: ODF/OdfNS.yaml
      policyName: "odf-subscription"
    - fileName: ODF/OdfOperGroup.yaml
      policyName: "odf-subscription"
    - fileName: ODF/OdfSubscription.yaml
      policyName: "odf-subscription"
      spec:
        source: mgmtcluster-operator-index
    - fileName: ODF/OdfStorageCluster.yaml
      policyName: "odf-subscription"
    #
    # OSPD operator
    #
#    - fileName: OSPDO/OspdONS.yaml
#      policyName: "ospd-subscription"
#    - fileName: OSPDO/OspdOCatalog.yaml
#      policyName: "ospd-subscription"
#    - fileName: OSPDO/OspdOOperGroup.yaml
#      policyName: "ospd-subscription"
#    - fileName: OSPDO/OspdOSubscription.yaml
#      policyName: "ospd-subscription"

    #
    # Service Mesh Installation (optional)
    #
    #- fileName: ISTIO/Jaeger-subs.yaml
    #  policyName: "sm-subscription"
    #  spec:
    #    source: mgmtcluster-operator-index
    #- fileName: ISTIO/Kiali-subs.yaml
    #  policyName: "sm-subscription"
    #  spec:
    #    source: mgmtcluster-operator-index
    #- fileName: ISTIO/ServMesh-subs.yaml
    #  policyName: "sm-subscription"
    #  spec:
    #    source: mgmtcluster-operator-index
    #- fileName: ISTIO/SmNs.yaml
    #  policyName: "sm-cp"
    #- fileName: ISTIO/ServMesh-CtrlPlane.yaml
    #  policyName: "sm-cp"

