---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "common-core"
  namespace: "policies-sub"
spec:
  bindingRules:
    # These policies will correspond to all clusters with this label:
    core: "true"
  sourceFiles:
    # Create operators policies that will be installed in all Core clusters
     
    #
    # Disable default operator catalogs
    #
    - fileName: OperatorHub.yaml
      remediationAction: enforce
      policyName: "disable-catalogs"
    - fileName: imageContentSource.yaml
      remediationAction: enforce
      policyName: "config-policy"
    - fileName: catalogSource.yaml
      remediationAction: enforce
      policyName: "config-policy"
