---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "common-core"
  namespace: "policies-sub"
spec:
  bindingRules:
    # These policies will correspond to all clusters with this label:
    core: "true"
  sourceFiles:
    # Create operators policies that will be installed in all Core clusters
     
    #
    # Disable default operator catalogs
    #
    - fileName: OperatorHub.yaml
      remediationAction: enforce
      policyName: "disable-catalogs"
    - fileName: catalogSourceMgmt.yaml
      remediationAction: enforce
      policyName: "config-cs"
    - fileName: imageContentSourcePolicyMgmt.yaml
      remediationAction: enforce
      policyName: "config-icsp"
    - fileName: mgmtcluster-ca-bundle.yaml
      remediationAction: enforce
      policyName: "config-mgmtcluster-ca"
    - fileName: mgmtcluster-to-proxy.yaml
      remediationAction: enforce
      policyName: "config-mgmtcluster-to-proxy"
    - fileName: ClusterVersionMgmt.yaml
      remediationAction: enforce
      policyName: "config-update-service"
    - fileName: allow-host-routing.yaml
      remediationAction: enforce
      policyName: "config-host-routing"


    # ODF operator
    #
    - fileName: ODF/OdfNS.yaml
      policyName: "odf-subscription"
    - fileName: ODF/OdfOperGroup.yaml
      policyName: "odf-subscription"
    - fileName: ODF/OdfSubscription.yaml
      policyName: "odf-subscription"
      spec:
        source: mgmtcluster-operator-index
#    - fileName: ODF/OdfStorageCluster.yaml
#      policyName: "odf-subscription"

    # PAO operator
    #
    - fileName: PaoSubscriptionNS.yaml
      policyName: "pao-subscription"
    - fileName: PaoSubscriptionOperGroup.yaml
      policyName: "pao-subscription"
    - fileName: PaoSubscription.yaml
      policyName: "pao-subscription"
      spec:
        source: mgmtcluster-operator-index
    - fileName: PAO/m2lcwl-master.yaml
      policyName: "pao-profile"
    - fileName: PAO/m2lcwl-worker.yaml
      policyName: "pao-profile"
    #
    # CNV operator
    #
    - fileName: CNV/CnvNS.yaml
      policyName: "cnv-subscription"
    - fileName: CNV/CnvOperGroup.yaml
      policyName: "cnv-subscription"
    - fileName: CNV/CnvSubscription.yaml
      policyName: "cnv-subscription"
      spec:
        source: mgmtcluster-operator-index
    - fileName: CNV/CnvHyperConverged.yaml
      policyName: "cnv-subscription"

    # Monitoring persistent storage and user workload
    - fileName: MON/UserWorkLoad.yaml
      remediationAction: enforce
      policyName: monitoring

    # Logging
    - fileName: LOG/log-ns.yaml
      remediationAction: enforce
      policyName: logging
    # Logging
    - fileName: LOG/installES.yaml
      remediationAction: enforce
      policyName: logging
      spec:
        source: mgmtcluster-operator-index
    - fileName: LOG/installLO-group.yaml
      remediationAction: enforce
      policyName: logging
    - fileName: LOG/installLO.yaml
      remediationAction: enforce
      policyName: logging
      spec:
        source: mgmtcluster-operator-index
    - fileName: LOG/loggingConfig.yaml
      remediationAction: enforce
      policyName: logging