apiVersion: v1
kind: Namespace
metadata:
  name: m2lcwl
  labels:
    kubernetes.io/metadata.name: m2lcwl
---
apiVersion: v1
kind: Namespace
metadata:
  name: akb-cwl
  labels:
    kubernetes.io/metadata.name: akb-cwl
---
apiVersion: v1
kind: Namespace
metadata:
  name: ztp-common
  labels:
    kubernetes.io/metadata.name: ztp-common