apiVersion: v1
kind: Namespace
metadata:
  name: cwl-m2l
  labels:
    kubernetes.io/metadata.name: cwl-m2l
---
apiVersion: v1
kind: Namespace
metadata:
  name: cwl-akb
  labels:
    kubernetes.io/metadata.name: cwl-akb

