---
apiVersion: v1
kind: Namespace
metadata:
  name: m2lcwl
  labels:
    kubernetes.io/metadata.name: m2lcwl
---
apiVersion: v1
kind: Namespace
metadata:
  name: akbcwl
  labels:
    kubernetes.io/metadata.name: akbcwl
---
apiVersion: v1
kind: Namespace
metadata:
  name: m2lsno1
  labels:
    kubernetes.io/metadata.name: m2lsno1
---
apiVersion: v1
kind: Namespace
metadata:
  name: m2lsno2
  labels:
    kubernetes.io/metadata.name: m2lsno2
---
apiVersion: v1
kind: Namespace
metadata:
  name: ztp-common
  labels:
    kubernetes.io/metadata.name: ztp-common
