apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-certs
  namespace: prom-kafka-adapter
  annotations:
    ran.openshift.io/ztp-deploy-wave: "5"
#
# Get the files: ca-bundle.crt, tls.key and tls.crt from MGMT cluster Kafka
# Use the contents of those files as is (no conversion to base64)
# to create the data for the config map
#
data:
  ca-bundle.crt: $ca
  tls.crt: $tls
  tls.key: $key
