#ConfgMap to setup storage and retention parameters for user workload monitoring.
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-workload-monitoring-config
  namespace: openshift-user-workload-monitoring
  annotations:
    ran.openshift.io/ztp-deploy-wave: "2"
data:
  config.yaml: |
    enableUserWorkload: true   
    alertmanagerMain:
      enableUserAlertmanagerConfig: true    
    prometheus:
      retention: 3d
      volumeClaimTemplate:
        spec:
          storageClassName: ocs-external-storagecluster-ceph-rbd
          resources:
            requests:
              storage: 20Gi
      enforcedSampleLimit: 50000
    thanosRuler:
      retention: 3d
      volumeClaimTemplate:
        spec:
          storageClassName: ocs-external-storagecluster-ceph-rbd
          resources:
            requests:
              storage: 20Gi
              
