apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: m2lcwl-worker
  labels:
    machineconfiguration.openshift.io/role: m2lcwl-worker
spec:
  machineConfigSelector:
    matchExpressions:
      - {key: machineconfiguration.openshift.io/role, operator: In, values: [worker, m2lcwl-worker]}
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/m2lcwl-worker: ""
  pause: false
