apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
# Common for all deployments
#- common.yaml

# Common for all Core deployments
- global/common-core.yaml
- global/common-core-secret.yaml

# Common for all RAN deployments
#- global/common-ran.yaml

# Specific to the cwl-site1 cluster
- cluster/Core/cwl-site1.yaml

# Specific to the cwl-site2 cluster
- cluster/Core/cwl-site2.yaml

resources:
- ns.yaml
