apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
# Common for all deployments
#- common.yaml

# Common for all Core deployments
- global/common-core.yaml

# Specific to the cwl-site1 cluster
- cluster/Core/m2lcwl.yaml

# Specific to the cwl-site2 cluster
- cluster/Core/akbcwl.yaml

resources:
#- ns.yaml
