apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
# Common for all deployments
#- common.yaml

# Common for all Core deployments
- global/common-core.yaml
- global/common-core-ca-cert.yaml

# Specific to the m2lcwl cluster
- cluster/Core/m2lcwl.yaml
- cluster/Core/m2lsno1.yaml
- cluster/Core/m2lsno2.yaml

# Specific to the akbcwl cluster
# - cluster/Core/akbcwl.yaml

resources:
#- ns.yaml
