apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: jaeger-product
  namespace: openshift-operators
  annotations:
    ran.openshift.io/ztp-deploy-wave: "12"
  labels:
    operators.coreos.com/jaeger-product.openshift-operators: ''
spec:
  source: mgmtcluster-operator-index
  sourceNamespace: openshift-marketplace
  name: jaeger-product
  channel: "stable"
  installPlanApproval: Manual
---
