apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: servicemeshoperator
  namespace: openshift-operators
  annotations:
    ran.openshift.io/ztp-deploy-wave: "12"
  labels:
    operators.coreos.com/servicemeshoperator.openshift-operators: ''
spec:
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  name: servicemeshoperator
  channel: "stable"
  installPlanApproval: Manual
---
