---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "akbcwl"
  namespace: "policies-sub"
spec:
  bindingRules:
    # These policies will correspond to all clusters with this label:
    cluster: akbcwl
  sourceFiles:
    # Create policies that will be installed only in a specific cluster

    # Masters Schedulable
    - fileName: mastersSchedulable.yaml
      policyName: "masters-schedulable"
      remediationAction: enforce
    #
    # Label node for Storage
    #
#    - fileName: LABEL/LabelNodeOCS.yaml
#      policyName: "label-nodes"
#      metadata:
#        name: master1.akbcwl.jnpr.bos2.lab
#    - fileName: LABEL/LabelNodeOCS.yaml
#      policyName: "label-nodes"
#      metadata:
#        name: master2.akbcwl.jnpr.bos2.lab
#    - fileName: LABEL/LabelNodeOCS.yaml
#      policyName: "label-nodes"
#      metadata:
#        name: master3.akbcwl.jnpr.bos2.lab
    #
    # Label node for MCP
    #
    - fileName: LABEL/LabelNodeRoleAkb.yaml
      policyName: "label-nodes"
      remediationAction: enforce
      metadata:
        labels:
          node-role.kubernetes.io/akbcwl-worker: ""
        name: auh-akb02-nec-nfvi2-rk06-cisco-docpwrk01.etisalat-nfvi.local
    - fileName: LABEL/LabelNodeRoleAkb.yaml
      policyName: "label-nodes"
      remediationAction: enforce
      metadata:
        labels:
          node-role.kubernetes.io/akbcwl-worker: ""
        name: auh-akb02-nec-nfvi2-rk07-cisco-docpwrk02.etisalat-nfvi.local

    - fileName: PAO/akbcwl-master.yaml
      policyName: "pao-profile"
    - fileName: PAO/akbcwl-worker.yaml
      policyName: "pao-profile"
      remediationAction: enforce

    - fileName: QUAY/quayInstance.yaml
      policyName: "quay-instance"
      metadata:
        name: akbcwl-registry
      remediationAction: enforce