---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "cwl-akb"
  namespace: "cwl-akb"
spec:
  bindingRules:
    # These policies will correspond to all clusters with this label:
    cluster: cwl-akb
  sourceFiles:
    # Create policies that will be installed only in a specific cluster

    #
    # Label node for Storage
    #
    - fileName: LABEL/LabelNodeOCS.yaml
      policyName: "label-nodes"
      metadata:
        name: master1.cwl-akb.jnpr.bos2.lab
    - fileName: LABEL/LabelNodeOCS.yaml
      policyName: "label-nodes"
      metadata:
        name: master2.cwl-akb.jnpr.bos2.lab
    - fileName: LABEL/LabelNodeOCS.yaml
      policyName: "label-nodes"
      metadata:
        name: master3.cwl-akb.jnpr.bos2.lab
    #
    # Label node for MCP
    #
    #- fileName: LABEL/LabelNodeRole.yaml
    #  policyName: "label-nodes"
    #  metadata:
    #    labels:
    #      node-role.kubernetes.io/profile1: ""
    #    name: worker151.cwl-akb.jnpr.bos2.lab
    
    #
    # Enable log forwarding to kafka
    #
    - fileName: LOG/ClusterLogForwarder.yaml
      policyName: "log-forwarder"
      spec:
        outputs:
           - name: infra-logs
             type: kafka
             url: tls://:mgnt-kafka-kafka-bootstrap-kafka-cluster.apps.mano-npss.jnpr.bos2.lab:443/cwl-akb-infra-logs
             secret:
               name: kafka-secret
           - name: audit-logs
             type: kafka
             url: tls://mgnt-kafka-kafka-bootstrap-kafka-cluster.apps.mano-npss.jnpr.bos2.lab:443/cwl-akb-audit-logs
             secret:
               name: kafka-secret
           - name: app-logs
             type: kafka
             url: tls://mgnt-kafka-kafka-bootstrap-kafka-cluster.apps.mano-npss.jnpr.bos2.lab:443/cwl-akb-app-logs
             secret:
               name: kafka-secret
        pipelines:
          - name: cwl-akb-infra-logs
            inputRefs:
            - infrastructure
            outputRefs:
            - infra-logs
            labels:
              logType: "infra"
          - name: cwl-akb-audit-logs
            inputRefs:
            - audit
            outputRefs:
            - audit-logs
            labels:
              logType: "audit"
          - name: cwl-akb-app-logs
            inputRefs:
            - application
            outputRefs:
            - app-logs
            labels:
              logType: "app"
 
    #
    # Deploy Prometheus Kafka Adapter
    #
    - fileName: MON/kafkaAdapDeployment.yaml
      policyName: "dply-prom-kafka-adapter"
      spec:
        template:
          spec:
            containers:
            - env:
              - name: KAFKA_BROKER_LIST
                value: mgnt-kafka-kafka-bootstrap-kafka-cluster.apps.mano-npss.jnpr.bos2.lab:443
              - name: KAFKA_TOPIC
                value: cwl-akb-ocp-metrics
