---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "m2lcwl"
  namespace: "policies-sub"
spec:
  bindingRules:
    # These policies will correspond to all clusters with this label:
    cluster: m2lcwl
  sourceFiles:
    # Create policies that will be installed only in a specific cluster


    # Masters Schedulable
    - fileName: mastersSchedulable.yaml
      policyName: "masters-schedulable"
      remediationAction: enforce
    #
    # Label node for Storage
    #
#    - fileName: LABEL/LabelNodeOCS.yaml
#      policyName: "label-nodes"
#      metadata:
#        name: master1.m2lcwl.jnpr.bos2.lab
#    - fileName: LABEL/LabelNodeOCS.yaml
#      policyName: "label-nodes"
#      metadata:
#        name: master2.m2lcwl.jnpr.bos2.lab
#    - fileName: LABEL/LabelNodeOCS.yaml
#      policyName: "label-nodes"
#      metadata:
#        name: master3.m2lcwl.jnpr.bos2.lab
    #
    # Label node for MCP
    #
    - fileName: LABEL/LabelNodeRole.yaml
      policyName: "label-nodes"
      remediationAction: enforce
      metadata:
        name: auh-m2l00-nec-nfvi2-rk01-dell-docpwrk01.m2lcwl.etisalat-nfvi.local
    - fileName: LABEL/LabelNodeRole.yaml
      policyName: "label-nodes"
      remediationAction: enforce
      metadata:
        name: auh-m2l00-nec-nfvi2-rk01-dell-docpwrk02.m2lcwl.etisalat-nfvi.local
    # Enable log forwarding to kafka
    #
#    - fileName: LOG/ClusterLogForwarder.yaml
#      policyName: "log-forwarder"
#      spec:
#        outputs:
#           - name: infra-logs
#             type: kafka
#             url: tls://mgnt-kafka-kafka-bootstrap-kafka-cluster.apps.mano-npss.jnpr.bos2.lab:443/m2lcwl-infra-logs
#             secret:
#               name: kafka-secret
#           - name: audit-logs
#             type: kafka
#             url: tls://mgnt-kafka-kafka-bootstrap-kafka-cluster.apps.mano-npss.jnpr.bos2.lab:443/m2lcwl-audit-logs
#             secret:
#               name: kafka-secret
#           - name: app-logs
#             type: kafka
#             url: tls://mgnt-kafka-kafka-bootstrap-kafka-cluster.apps.mano-npss.jnpr.bos2.lab:443/m2lcwl-app-logs
#             secret:
#               name: kafka-secret
#        pipelines:
#          - name: m2lcwl-infra-logs
#            inputRefs:
#            - infrastructure
#            outputRefs:
#            - infra-logs
#            labels:
#              logType: "infra"
#          - name: m2lcwl-audit-logs
#            inputRefs:
#            - audit
#            outputRefs:
#            - audit-logs
#            labels:
#              logType: "audit"
#          - name: m2lcwl-app-logs
#            inputRefs:
#            - application
#            outputRefs:
#            - app-logs
#            labels:
#              logType: "app"
 
    #
    # Deploy Prometheus Kafka Adapter
    #
#    - fileName: MON/kafkaAdapDeployment.yaml
#      policyName: "dply-prom-kafka-adapter"
#      spec:
#        template:
#          spec:
#            containers:
#            - env:
#              - name: KAFKA_BROKER_LIST
#                value: mgnt-kafka-kafka-bootstrap-kafka-cluster.apps.mano-npss.jnpr.bos2.lab:443
#              - name: KAFKA_TOPIC
#                value: m2lcwl-ocp-metrics
