---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "m2lcwl"
  namespace: "policies-sub"
spec:
  bindingRules:
    # These policies will correspond to all clusters with this label:
    cluster: m2lcwl
  sourceFiles:
    # Create policies that will be installed only in a specific cluster


    # Masters Schedulable
    - fileName: mastersSchedulable.yaml
      policyName: "masters-schedulable"
      remediationAction: enforce
    #
    # Label node for Storage
    #
#    - fileName: LABEL/LabelNodeOCS.yaml
#      policyName: "label-nodes"
#      metadata:
#        name: master1.m2lcwl.jnpr.bos2.lab
#    - fileName: LABEL/LabelNodeOCS.yaml
#      policyName: "label-nodes"
#      metadata:
#        name: master2.m2lcwl.jnpr.bos2.lab
#    - fileName: LABEL/LabelNodeOCS.yaml
#      policyName: "label-nodes"
#      metadata:
#        name: master3.m2lcwl.jnpr.bos2.lab
    #
    # Label node for MCP
    #
    - fileName: LABEL/LabelNodeRole.yaml
      policyName: "label-nodes"
      remediationAction: enforce
      metadata:
        name: auh-m2l00-nec-nfvi2-rk01-dell-docpwrk01
    - fileName: LABEL/LabelNodeRole.yaml
      policyName: "label-nodes"
      remediationAction: enforce
      metadata:
        name: auh-m2l00-nec-nfvi2-rk01-dell-docpwrk02

    - fileName: PAO/m2lcwl-master.yaml
      policyName: "pao-profile"
    - fileName: PAO/m2lcwl-worker.yaml
      policyName: "pao-profile"
      remediationAction: enforce

    - fileName: QUAY/quayInstance.yaml
      policyName: "quay-instance"
      metadata:
        name: m2lcwl-registry
      remediationAction: enforce