apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: quay-operator
  namespace: quay-enterprise
spec:
  sourceNamespace: openshift-marketplace
  # Modify source name of the catalogsource for air-gapped deployments
  source: redhat-operators
  channel: stable-3.8
  installPlanApproval: Automatic
  name: quay-operator
